sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: RmVLW6VZGnf5XhJ0lxWA8UrezVRS22aQTJ9dY7oIPIzD/UHdrg4+NxBJIHtwcpSLu/ska7OCUxV+fC8qe7BNfD31cslvVfm60yIxa4zbXvi9dhqITRrrFKplYsV2odXH2WE57eIZ6WMnQiI55bSUc1AuEpxDDN6FAF6tBFMym7i9VcyNQUXfsONwISBehNB6V60CwL/2kz+ho7A1HQQ4ZR0uGFyD976Sef6iVD1XiQL1BD5POnTYdjKYxlcRsPvVFLrfMIcgj6+ZvhEsCT0E6pjk+J0zzsJ82G+9WDD/426PttrEbtsWbIXRfswH5vzWz1+0elAELRaxZIvEriBRXahXu2RAW29H3MNCGa35HPLzKI3ppgJGkecXiaRd6cGjNZx4gMSjSe/ErLoVqVDou35BNuVW4pIBPgtWxdDSRXLSfIPol6vuUezZyZZah9BZKU+cS1DlMVSoVMIe6hkcfUjg72HYZJQTH4caB3fgJdPfWh5+6lsKhbjGPdcdSFAe2gZLocTVhzikfFTYW7S2cuAv94hrQhW9JWjXWpevApvs6K/L82NQI2gen7JvsDGbkbRayCETMGSK7iczyJWEW0aGydG1VCMHGWPRB9G0X0JKdHcRz55m8lLISovr2hNN2G/d27QBpG3e2It4lDCNC86sSNZI004GhZirspu3TLc=
