sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: RmVLW6VZGnf5XhJ0lxWA8UrezVRS22aQTJ9dY7oIPIzD/UHdrg4+NxBJIHtwcpSLu/ska7OCUxV+fC8qe7BNfD31cslvVfm60yIxa4zbXvi9dhqITRrrFKplYsV2odXH2WE57eIZ6WMnQiI55bSUc1AuEpxDDN6FAF6tBFMym7i9VcyNQUXfsONwISBehNB6V60CwL/2kz+ho7A1HQQ4ZR0uGFyD976Sef6iVD1XiQL1BD5POnTYdjKYxlcRsPvVFLrfMIcgj6+ZvhEsCT0E6pjk+J0zzsJ82G+9WDD/426PttrEbtsWbIXRfswH5vzWz1+0elAELRaxZIvEriBRXahXu2RAW29H3MNCGa35HPLzKI3ppgJGkecXiaRd6cGjNZx4gMSjSe/ErLoVqVDou35BNuVW4pIBPgtWxdDSRXLSfIPol6vuUezZyZZah9BZKU+cS1DlMVSoVMIe6hkcfUjg72HYZJQTH4caB3fgJdPfWh5+6lsKhbjGPdcdSFAe2gZLocTVhzikfFTYW7S2cuAv94hrQhW9JWjXWpevApvs6K/L82NQI2gen7JvsDGbkbRayCETMGSK7iczyJWEW0aGydG1VCMHGWPRB9G0X0JKdHcRz55m8lLISovr2hNN2G/d27QBpG3e2It4lDCNC86sSNZI004GhZirspu3TLc=
  - secure: BxwdlL2Se4Ak6PlW/YwAzZ6N21nok8U06GiWV4burnH28xVNlbMVzbwUbR3Xzpi7n52aVwuXsXTGkUw7wwYd9PgwakjdpGmh+mjQRVen2P7NCvNRDG0O66aEyp8LUblncbTA6UTAFuK7ovtkz1WlI5J4C0tyZ2DazxBgTxMvU6PXjW5oEe1FBEBNe7bgHted3XYfPOVUEa+OlZ+06bFU6WSbmLJWH0shvHu78mLBRjzCK3q1sZfRq7MEGK1JGeFYqOkbSfsF+zwmG9bz0mMZIULRHb9q5gy9zrbU750lAcUNNzjXIEUvwrALjYwINQlTLCyJiPVZj3AvytTvg5enm8Wm6D6iIKQCf6IBp/mZAzPOjhZSlfZBoLTQhyGVECd8C3PasIYznkJ1o1KVPwc4HdM1EGtujeleyYDhjRDtKQN+q2/VmfTLcVe0KKEB6+iHyzlLAauszp27OYIMOWvYfM7FpfC66dLSKFHMUSg1nd6eq0PuFkoykeZ9semD76SjHm49+o+A2TrJg/wgliwMLyP1sCMyfGLWHhYbttdR0b5WQcn+425ej2WnD35ylJ3Oh2WU5JcVLiyqC6tMN/MZqQ3zD+AK2Z9g9jBCuAFG5Kot0rMEUY0K+VFG3ocBUooR19r4mZwmuDZHL9RhgC0/rjPN4ZIe0fdQjFfjrI1s/zg=
  - secure: CnAnVRWosusY3DbR/dUxbFkit2DcjZBcI1AEgv14Bo6HCuKYc9vPLm76F7ksBkzGPbfzEAjO5pAyATRyC2ATSQVQYG2LhB5kChGpKfK2apDfwGqKtLRoazIfQLvt/uROakA891M8WJUZLSq4YXN/Hsk3A5tpQV+Wm4jZOWgU7k3hIMalM+O3ZKqvJJtiscIhiqGFm1V+KlQM7DhBChwqozxXzHVVJJCvzFwArGTm/0DX58l8hw+LhriALJuArR0uOhtdicNzCZLg3otPPhOSNQSSCeqpCqGHSSjIBSA3D/+ZB0nUf21EOG+LtHTHfIfJ10ZfKpRKUBWYXr6Sa9O1nYR0q9BpALfi9jLPUCU4yCh0El4lWzCipkEEI0Edj5q98EtLIyOchne/3saizpjuDkl2npFCmCwYnXIXHbyhRXE8Q+IvY9BdPMNPlMNMwUU9smEq0VhOHPYR29p1+WgOScOSP8RtxckCrNKkyegVJGg9Ne9LnTNNAUQETo4we4OeaCX3wBfxJbTW/eSUerFyg/r+D0xZmMUdUZOCll0OS/zOFmQUeAUtDc9rdJzJx2HfDpQoqYOjDluywTar45U9vNQlADCyc9TL5f//X/lMbz18nPkxpiYG3NXXCZ3yuV3ok+vIi1jPZ2WZJub2Kv0FpwUcB5JVeq9n1wiUYBxEuK8=
  - secure: qF46LbDA+lVgIMWI++MJlQ8/ztC31qVXMY1TjSze8WTmn82SzJhiw7NutVQ8CPxWvdBDIoF/UmXTqW/esKbF/0HnFaQB9xMXXP6xm6B1vPldeGVcCgG4JQQQIubbpJI6jESOCc6dghCkQb/LsSnLdCArRf86f5L5vvfMrB+9jD7GgoNHr6BRLB0KFXbyeJRd8s+L0beycxQ702ABXBsFrnDF4xGkEQWqvoLUs3PCI2uPNp5JKphmw5tg3ej/ouwZygJuuKNuuKchOLvLSElQ/XdfctkgiWyRnRPNEBfifT5uyZuwIxZno/KJONzjfYAOocqsGOds2w71975sPPA31lPjB5WdGTD9UMsnoL/lGxmQo5XeVTG2VKS19LYl/MNNyTDRjDvJ9K4Fy5qDlLsnZV0SYrqqfM2bmVtR+JIFUQaNmOgpUYv/Co5uRdymZPGHw9N1vc4aIeKhtThtIW1vgxbPkpbS29AKo7kav1tlYo9F0mwshQ4ZJ8MEqdv3YzFSNEawEGqJhlsAAqb7GWtaeuWIJ3Q/snU/WZIB34x3V/SwlA2vhg1A1rfmBqJJZ+JP0WLL3N2tIBmdle5z/bHFrNaxPe4ukcRT8xZVPr46Cj2nnqKgLVdWuhMLyUo0PchPjR6uqqJJfI++3d9c+9DeHjajIzAnC1wleIT8bPUQvtc=
